-- CreateTable: InsightRecommendation
-- Persisted recommendation generated by the insights engine for a project.
CREATE TABLE "InsightRecommendation" (
    "id"          TEXT NOT NULL,
    "projectId"   TEXT NOT NULL,
    "type"        TEXT NOT NULL,
    "title"       TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "priority"    INTEGER NOT NULL DEFAULT 50,
    "riskLevel"   TEXT NOT NULL DEFAULT 'MEDIUM',
    "actionLevel" TEXT NOT NULL DEFAULT 'MANUAL_APPLY',
    "payloadJson" JSONB,
    "status"      TEXT NOT NULL DEFAULT 'OPEN',
    "source"      TEXT NOT NULL DEFAULT 'COVERAGE',
    "createdAt"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "appliedAt"   TIMESTAMP(3),
    "dismissedAt" TIMESTAMP(3),

    CONSTRAINT "InsightRecommendation_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "InsightRecommendation_projectId_status_idx" ON "InsightRecommendation"("projectId", "status");
CREATE INDEX "InsightRecommendation_projectId_source_idx"  ON "InsightRecommendation"("projectId", "source");

-- CreateTable: MonitoringProfile
-- Reusable installable bundle of checks, alert mappings, and diagnostic rules.
CREATE TABLE "MonitoringProfile" (
    "id"             TEXT NOT NULL,
    "key"            TEXT NOT NULL,
    "name"           TEXT NOT NULL,
    "providerType"   TEXT NOT NULL,
    "description"    TEXT NOT NULL,
    "definitionJson" JSONB NOT NULL,
    "isSystem"       BOOLEAN NOT NULL DEFAULT false,
    "createdAt"      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "MonitoringProfile_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "MonitoringProfile_key_key" ON "MonitoringProfile"("key");

-- CreateTable: SyntheticJourney
-- Tracked end-to-end user journey for a project.
CREATE TABLE "SyntheticJourney" (
    "id"             TEXT NOT NULL,
    "projectId"      TEXT NOT NULL,
    "name"           TEXT NOT NULL,
    "type"           TEXT NOT NULL DEFAULT 'BROWSER',
    "status"         TEXT NOT NULL DEFAULT 'DRAFT',
    "definitionJson" JSONB NOT NULL,
    "lastRunAt"      TIMESTAMP(3),
    "lastStatus"     TEXT,
    "createdById"    TEXT,
    "createdAt"      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "SyntheticJourney_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "SyntheticJourney_projectId_status_idx" ON "SyntheticJourney"("projectId", "status");

-- CreateTable: CoverageTarget
-- A specific area that a project should have monitored, tracked for gap visibility.
CREATE TABLE "CoverageTarget" (
    "id"             TEXT NOT NULL,
    "projectId"      TEXT NOT NULL,
    "targetType"     TEXT NOT NULL,
    "targetKey"      TEXT NOT NULL,
    "label"          TEXT NOT NULL,
    "criticality"    TEXT NOT NULL DEFAULT 'HIGH',
    "isCovered"      BOOLEAN NOT NULL DEFAULT false,
    "coverageSource" TEXT,
    "detailsJson"    JSONB,
    "updatedAt"      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "CoverageTarget_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "CoverageTarget_projectId_isCovered_idx" ON "CoverageTarget"("projectId", "isCovered");
CREATE UNIQUE INDEX "CoverageTarget_projectId_targetKey_key" ON "CoverageTarget"("projectId", "targetKey");

-- CreateTable: InsightActionRun
-- Execution record for an applied or dismissed insight recommendation.
CREATE TABLE "InsightActionRun" (
    "id"                       TEXT NOT NULL,
    "projectId"                TEXT NOT NULL,
    "insightRecommendationId"  TEXT,
    "actionType"               TEXT NOT NULL,
    "status"                   TEXT NOT NULL DEFAULT 'PENDING',
    "requestedById"            TEXT,
    "approvedById"             TEXT,
    "resultJson"               JSONB,
    "errorMessage"             TEXT,
    "createdAt"                TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completedAt"              TIMESTAMP(3),

    CONSTRAINT "InsightActionRun_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "InsightActionRun_projectId_status_idx"                ON "InsightActionRun"("projectId", "status");
CREATE INDEX "InsightActionRun_projectId_createdAt_idx"             ON "InsightActionRun"("projectId", "createdAt" DESC);
CREATE INDEX "InsightActionRun_insightRecommendationId_idx"         ON "InsightActionRun"("insightRecommendationId");
