export enum ProjectStatus {
	HEALTHY = "HEALTHY",
	DEGRADED = "DEGRADED",
	DOWN = "DOWN",
	PAUSED = "PAUSED"
}

export enum ServiceType {
	FRONTEND = "FRONTEND",
	API = "API",
	DATABASE = "DATABASE",
	WORKER = "WORKER",
	WEBHOOK = "WEBHOOK",
	EMAIL = "EMAIL",
	PAYMENT = "PAYMENT",
	THIRD_PARTY = "THIRD_PARTY"
}

export enum CheckType {
	HTTP = "HTTP",
	SSL = "SSL",
	KEYWORD = "KEYWORD",
	RESPONSE_TIME = "RESPONSE_TIME",
	HEARTBEAT_STALE = "HEARTBEAT_STALE"
}

export enum CheckStatus {
	PASS = "PASS",
	FAIL = "FAIL",
	WARN = "WARN"
}

export enum AlertSeverity {
	INFO = "INFO",
	LOW = "LOW",
	MEDIUM = "MEDIUM",
	HIGH = "HIGH",
	CRITICAL = "CRITICAL"
}

export enum AlertStatus {
	OPEN = "OPEN",
	ACKNOWLEDGED = "ACKNOWLEDGED",
	RESOLVED = "RESOLVED"
}

export enum IncidentStatus {
	OPEN = "OPEN",
	INVESTIGATING = "INVESTIGATING",
	MONITORING = "MONITORING",
	RESOLVED = "RESOLVED"
}

export enum EventType {
	BOOKING_FAILED = "BOOKING_FAILED",
	PAYMENT_FAILED = "PAYMENT_FAILED",
	WEBHOOK_FAILED = "WEBHOOK_FAILED",
	EMAIL_FAILED = "EMAIL_FAILED",
	AUTH_SPIKE = "AUTH_SPIKE",
	CRON_MISSED = "CRON_MISSED",
	GOOGLE_API_FAILED = "GOOGLE_API_FAILED",
	DEPLOYMENT_STARTED = "DEPLOYMENT_STARTED",
	DEPLOYMENT_FINISHED = "DEPLOYMENT_FINISHED"
}
